// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWMHVSK_N_OpH8sv9nQt7sf0rqqoH1Sfs',
    appId: '1:741118982258:web:213946bbde8afdb209aaeb',
    messagingSenderId: '741118982258',
    projectId: 'flutter-996e3',
    authDomain: 'flutter-996e3.firebaseapp.com',
    storageBucket: 'flutter-996e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbrTBc2vRFqlf1J0WklAso-yzYTklxxFw',
    appId: '1:741118982258:android:2736469b35a9583109aaeb',
    messagingSenderId: '741118982258',
    projectId: 'flutter-996e3',
    storageBucket: 'flutter-996e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBULUx6nhZJ9oPrMkeThoD8H3ipD0pbAYQ',
    appId: '1:741118982258:ios:7ea19817eff0edde09aaeb',
    messagingSenderId: '741118982258',
    projectId: 'flutter-996e3',
    storageBucket: 'flutter-996e3.appspot.com',
    iosClientId: '741118982258-kmi3uts50og8ul8rtk7mk08f7ji38c93.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBULUx6nhZJ9oPrMkeThoD8H3ipD0pbAYQ',
    appId: '1:741118982258:ios:7ea19817eff0edde09aaeb',
    messagingSenderId: '741118982258',
    projectId: 'flutter-996e3',
    storageBucket: 'flutter-996e3.appspot.com',
    iosClientId: '741118982258-kmi3uts50og8ul8rtk7mk08f7ji38c93.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
